### PR TITLE
Fix error 'Use of uninitialized value'

### PR DESCRIPTION
**Pull request by LukasWillin**
Hey Luke!

Thanks for this amazing piece of code!

Had trouble with some input resulting in the following errors.
`Use of uninitialized value $__temp_string`
And after I fixed them for $__temp_string got the following
`Use of uninitialized value $column`

So I did some changes to get rid of them.
Your tests have ran successfully in /bin/bash on SLES 12.
image

Be aware that this is my first time working with perl so I guess you should be extra critical of my changes made.

Let me know if you need anything from me.

Best Regards
Lukas

### CODE REVIEW

**Comment by LukasWillin** [comment]
Did a bit of cleanup after yesterdays rush

**Comment by LukeSavefrogs** [comment]
I'll try to analyze whatr you did and merge the PR. 

Thank you so much for your help and effort 😊

**Comment by LukeSavefrogs** [comment]
Thank you for your contribution to this small project 😄 

My goal is to add a switch that will allow to choose between keeping and removing white lines (`--keep-empty-lines`), and your code is a good starting point.

Have a good day! 😄🎉

**Comment by LukeSavefrogs** [comment]
@all-contributors please add @LukasWillin for bug, code, tests

**Pull request merged**
